begin;
select plan(26);

select has_table('public'::name, 'actors'::name);
select has_table('public'::name, 'activity_events'::name);
select has_table('public'::name, 'approvals'::name);
select has_table('public'::name, 'integration_outbox'::name);
select col_is_pk('public'::name, 'actors'::name, 'id'::name);
select col_is_pk('public'::name, 'activity_events'::name, 'id'::name);
select col_is_pk('public'::name, 'approvals'::name, 'id'::name);
select col_is_pk('public'::name, 'integration_outbox'::name, 'id'::name);
select col_not_null('public'::name, 'activity_events'::name, 'actor_id'::name);
select col_not_null('public'::name, 'approvals'::name, 'requested_by_actor_id'::name);
select col_not_null('public'::name, 'integration_outbox'::name, 'idempotency_key'::name);
select col_not_null('public'::name, 'integration_outbox'::name, 'correlation_id'::name);
select ok((select relrowsecurity from pg_class where oid = 'public.actors'::regclass), 'actors has row-level security enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.activity_events'::regclass), 'activity_events has row-level security enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.approvals'::regclass), 'approvals has row-level security enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.integration_outbox'::regclass), 'integration_outbox has row-level security enabled');
select policies_are('public', 'actors', array['No direct actor access']::name[]);
select policies_are('public', 'activity_events', array['No direct activity access']::name[]);
select policies_are('public', 'approvals', array['No direct approval access']::name[]);
select policies_are('public', 'integration_outbox', array['No direct outbox access']::name[]);
select table_privs_are('public', 'actors', 'authenticated', array[]::name[]);
select table_privs_are('public', 'activity_events', 'authenticated', array[]::name[]);
select table_privs_are('public', 'approvals', 'authenticated', array[]::name[]);
select table_privs_are('public', 'integration_outbox', 'authenticated', array[]::name[]);
select has_index('public'::name, 'approvals'::name, 'approvals_requester_idempotency_key_idx'::name);
select has_index('public'::name, 'integration_outbox'::name, 'integration_outbox_destination_idempotency_key_idx'::name);

select * from finish();
rollback;
