begin;
select plan(26);
select has_table('public', 'organizations'); select has_table('public', 'customers');
select has_table('public', 'customer_contacts'); select has_table('public', 'service_locations');
select col_is_pk('public', 'organizations', 'id'); select col_is_pk('public', 'customers', 'id');
select col_not_null('public', 'customer_contacts', 'value'); select col_not_null('public', 'customer_contacts', 'normalized_value');
select col_not_null('public', 'service_locations', 'address_line_1');
select row_security_active('public.organizations'); select row_security_active('public.customers');
select row_security_active('public.customer_contacts'); select row_security_active('public.service_locations');
select policies_are('public', 'organizations', array['No direct organization access']);
select policies_are('public', 'customers', array['No direct customer access']);
select policies_are('public', 'customer_contacts', array['No direct customer contact access']);
select policies_are('public', 'service_locations', array['No direct service location access']);
select table_privs_are('public', 'organizations', 'authenticated', array[]::text[]);
select table_privs_are('public', 'customers', 'authenticated', array[]::text[]);
select table_privs_are('public', 'customer_contacts', 'authenticated', array[]::text[]);
select table_privs_are('public', 'service_locations', 'authenticated', array[]::text[]);
select has_index('public', 'customer_contacts', 'customer_contacts_primary_customer_kind_idx');
select has_index('public', 'customer_contacts', 'customer_contacts_primary_organization_kind_idx');
select has_index('public', 'customers', 'customers_organization_id_idx');
select has_index('public', 'service_locations', 'service_locations_organization_id_idx');
select has_index('public', 'service_locations', 'service_locations_customer_id_idx');
select * from finish();
rollback;
