const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs');
test('Calendar schedule and reschedule controls are owner/admin-only, timezone-explicit, and explain safe failure states', () => {
  const source = fs.readFileSync('command/calendar-operations.js', 'utf8');
  assert.match(source, /\['owner', 'admin'\]/); assert.match(source, /calendar_availability_conflict/); assert.match(source, /canonical_completion_rolled_back/); assert.match(source, /reconciliation_needed/); assert.match(source, /Saving safely/);
  assert.match(source, /function zonedLocalToIso/); assert.match(source, /timeZoneName: 'longOffset'/); assert.match(source, /ambiguous or unavailable/);
  assert.match(source, /Scheduled ·/); assert.match(source, /Reschedule/); assert.match(source, /name="timezone"/); assert.match(source, /timezoneOptions/);
  assert.match(source, /data-calendar-action="schedule"/); assert.match(source, />Schedule</); assert.match(source, /existing client record/);
  assert.match(source, /const form = dialog\.querySelector\('form'\)/);
  assert.match(source, /form\.elements\.timezone/);
  assert.doesNotMatch(source, /dialog\.elements/);
  assert.match(source, /event\.preventDefault\(\); event\.stopPropagation\(\)/);
  assert.match(source, /dialog\.showModal\(\)/);
  assert.match(source, /type="button" value="cancel" data-cancel-schedule/);
  assert.match(source, /dialog\.close\('cancel'\)/);
  assert.match(source, /event\.target === dialog/);
  assert.match(source, /No appointment was created/);
  assert.doesNotMatch(source, /Open booking/); assert.doesNotMatch(source, /\/book\.html/);
  assert.match(source, /Operator remains read-only/); assert.match(source, /Technician sees none/);
  assert.doesNotMatch(source, /payload\.startAt = new Date\(start\)\.toISOString\(\)/);
});
