(() => {
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const titleCase = value => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase());
  const formatDate = value => value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : 'No timestamp';
  const badge = state => state === 'attention' || state === 'needs_attention' || state === 'reconciliation_needed' ? 'amber' : state === 'healthy' || state === 'delivered' || state === 'succeeded' ? 'green' : 'gray';
  const stateLabel = state => state === 'not_yet_instrumented' ? 'Not instrumented' : titleCase(state);
  async function loadHistory() { const response = await fetch('/api/command-data?resource=health', { credentials: 'same-origin', headers: { Accept: 'application/json' } }); if (response.status === 401) { window.location.assign('/command/login/'); throw new Error('authentication_required'); } const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error || 'command_history_read_failed'); return payload.data?.integrationHistory; }
  function sourceRow(name, source, note) { const state = source?.state || 'unavailable'; return `<div class="health-row"><span class="health-dot ${badge(state) === 'amber' ? 'warn' : ''}"></span><div><div class="health-name">${escapeHtml(name)}</div><div class="health-note">${escapeHtml(note)}</div></div><span class="badge ${badge(state)}">${escapeHtml(stateLabel(state))}</span></div>`; }
  function row(item) { const label = item.kind === 'calendar_operation' ? `${titleCase(item.operation)} Calendar operation` : `${titleCase(item.eventType)} · ${titleCase(item.kind)}`; const detail = `${formatDate(item.occurredAt)}${item.errorCode ? ` · ${item.errorCode}` : ''}`; return `<div class="list-row"><div class="row-icon">${item.kind === 'resend' ? '✉' : item.kind === 'notion' ? 'N' : '◇'}</div><div><div class="row-name">${escapeHtml(label)}</div><div class="row-sub">${escapeHtml(detail)}</div></div><span class="badge ${badge(item.state)}">${escapeHtml(stateLabel(item.state))}</span></div>`; }
  function render(history) { const section = document.querySelector('[data-section="messages"]'); if (!section || !history) return renderFailure(); const calendarNote = history.calendar.recordedOperations ? `${history.calendar.recordedOperations} recorded operation${history.calendar.recordedOperations === 1 ? '' : 's'} · ${history.calendar.reconciliationNeeded} need reconciliation` : 'No Calendar operation receipt recorded yet'; const rows = [sourceRow('Transactional email receipts', history.email, history.email.recordedEvents ? `${history.email.recordedEvents} recorded delivery event${history.email.recordedEvents === 1 ? '' : 's'} · recipient details withheld` : 'Not yet instrumented — Command does not infer delivery from server logs'), sourceRow('Google Calendar reconciliation', history.calendar, calendarNote), sourceRow('Notion mirror events', history.notion, history.notion.recordedEvents ? `${history.notion.recordedEvents} recorded mirror event${history.notion.recordedEvents === 1 ? '' : 's'}` : 'Not yet instrumented — no mirror status is assumed')].join(''); section.innerHTML = `<div class="section-header"><div class="eyebrow">Operational history · Live read-only</div><h2>Messages</h2><p>Recorded transactional and integration evidence, without conversation content or contact details.</p></div><div class="card panel"><div class="panel-head"><div><div class="panel-title">Integration evidence</div><div class="row-sub">Durable server-side records only</div></div><span class="badge blue">Read-only</span></div><div class="health">${rows}</div></div><div class="card panel"><div class="panel-head"><div class="panel-title">Recent recorded activity</div><span class="badge ${history.timeline.length ? 'blue' : 'gray'}">${history.timeline.length ? `${history.timeline.length} events` : 'Empty'}</span></div>${history.timeline.map(row).join('') || '<div class="empty"><div class="empty-icon">✦</div><strong>No recorded communication or integration events</strong><span>Command is not substituting message fixtures or provider assumptions.</span></div>'}</div><div class="prototype-note">Read-only operational history · no messages, Calendar events, or mirrors can be changed here</div>`; }
  function renderFailure() { const section = document.querySelector('[data-section="messages"]'); if (!section) return; section.innerHTML = '<div class="section-header"><div class="eyebrow">Operational history · Live read-only</div><h2>Messages</h2><p>Recorded transactional and integration evidence, without conversation content or contact details.</p></div><div class="card"><div class="empty"><div class="empty-icon">!</div><strong>Recorded history unavailable</strong><span>Command failed closed. No fixture communications or assumed integration state was substituted.</span></div></div>'; }
  window.addEventListener('DOMContentLoaded', async () => { try { render(await loadHistory()); } catch { renderFailure(); } }, { once: true });
})();
